# Generated by Django 4.2.29 on 2026-04-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0002_grouptask_priority_taskmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptask',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='task_attachments/'),
        ),
        migrations.AddField(
            model_name='grouptask',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or references'),
        ),
    ]
