# Generated by Django 4.2.29 on 2026-04-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0003_grouptask_attachment_grouptask_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptask',
            name='notes',
        ),
    ]
