# Generated by Django 4.2.29 on 2026-04-12 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0004_remove_grouptask_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTaskChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='collaboration.grouptask')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
