# Generated by Django 4.2.29 on 2026-03-21 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('class', 'Class'), ('assignment', 'Assignment'), ('personal', 'Personal'), ('extracurricular', 'Extracurricular'), ('study', 'Study Session'), ('exam', 'Exam')], default='personal', max_length=30)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#4A90D9', max_length=7)),
                ('all_day', models.BooleanField(default=False)),
                ('recurrence', models.CharField(blank=True, choices=[('', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('professor', models.CharField(blank=True, max_length=100)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(default='#0D3B66', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
